gems: [jekyll-paginate]

markdown: kramdown

# Sass settings
sass:
    sass_dir: css
    style: compressed

paginate: 5
paginate_path: /blog/page/:num/
  
collections:
  articles:
    output: true
    permalink: :path/

  pages:
    output: true
    permalink: :path/