gems: [jekyll-paginate-v2]

markdown: kramdown

# Sass settings
sass:
    sass_dir: css
#    style: compressed

plugins_dir:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
#paginate: nil
#paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
############################################################
# Old jekyll-paginate pagination logic
#   Uncomment thew two entries below to demonstrate how this new gem
#   retains backwards compatibility with the old pagination logic 
#   AS OF JANUARY 2018 this code does not work anymore!
#paginate: 3
#paginate_path: "/legacy/page:num/"

collections:
  articles:
    output: true
    permalink: :path/

  pages:
    output: true
    permalink: :path/